name: ci

on: [push]

jobs:
  integration:
    env:
      TEST_SQUARE_TOKEN: ${{ secrets.TEST_SQUARE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Run integration tests
        run: yarn && yarn test:integration
